### ISSUE TITLE
About pathway enrichment tests

### ISSUE THREAD

**Issue by llrs** [zhilongjia/cogena#4]
The packages uses it's own function to load GMT files. Would it be better to use already implemented functions like those from GSEABase?
Could it be possible to use enrichment analysis of other packages of Bioconductor and to use the Enrichment score instead of testing the -log2(FDR)?

**Comment by zhilongjia** [comment]
Bugs for my custom loading GMT file code? Why GSEAbase is better? 
Please give some examples of the methods of enrichment analysis from other packages, which are suitable for the cogena situation. Thank you.

**Comment by llrs** [comment]
I didn't find bugs. But it is standard to use code that is already written to avoid bugs and redoing things. GSEABase is a package maintained by Bioconductor team, so it is better integrated in Bioconductor. If you don't need to do it, it is just a suggestion.

The enrichment scores I would like to use come from the `fgsea` and the `topGO` package.

**Comment by zhilongjia** [comment]
As the implemented code of `gmt2list` in `cogena` is short, I do not think import  GSEABase is better in this situation. Anyway, not a key problem.

**Co-expressed genes are a gene vector with no weight so far. And the gene set used here are a list of genes.** They are the input for the test. Because the ranked all gene list is necessary for `gsea`, `PAGE` or `ks`,  they are not suitable for cogena pathway analysis, but suitable for cogena drug repositioning analysis with CMap rank dataset as gene set, which makes structure of gene sets in cogena complex. Actually, I implemented GSEA or PAGE (not sure which one I tested) in cogena for drug repositioning years ago, but qualitatively no signaficant difference with hypergeometric test when the test psoriasis datasets were tested. BTW, I uploaded the PAGE package at [Github](https://github.com/zhilongjia/PAGE) years ago.

Generally, results of the fisher test is very similar to those of hypergeometric test. To be honst, I'm not familar with other tests in the `topGO` package. If you find some good test methods in practice please tell me. 

I probably implement more tests in future, while not recently, as more tests means more tries for the analysis. Thank you.
